server:
    port: 8888

spring:
    data:
        mongodb:
            authentication-database: admin
            username: rootuser
            password: rootpass
            database: test
            port: 27017
            host: localhost
            auto-index-creation: true